# Site settings
title: MatthewWynn.com
description: > # this means to ignore newlines until "baseurl:"
   Just a site for my things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://matthewwynn.com" # the base hostname & protocol for your site
github_username:  m-wynn

# Build settings
markdown: kramdown
